"""Extended Laguerre hierarchy generated by the SOH two-body partition.

For a real entire function ``f`` and real ``x``, define

    Q_x(q) = 1/2 f(x+i*sqrt(q)) f(x-i*sqrt(q)).

The product is even in ``sqrt(q)``, hence Q_x is an entire function of q. Its
Taylor coefficients are exactly one half of the classical extended Laguerre
operators L_n[f](x) of Csordas--Patrick--Varga / Cardon:

    Q_x(q) = 1/2 sum_{n>=0} L_n[f](x) q^n.

For the Riemann Xi function, Cardon's theorem gives the exact RH-equivalent
cone L_n[Xi](x) >= 0 for every real x and every n >= 0. This module records
the algebra and finite regression controls only; it does not prove RH.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence

import mpmath as mp

from .theta_nbody_rigidity import hermitian_jensen_value, xi_fourier_entire

ComplexFn = Callable[[mp.mpc], mp.mpc]


def transverse_q_coefficient(
    f: ComplexFn, x: float | mp.mpf, n: int
) -> mp.mpf:
    r"""Return the q^n coefficient of ``Q_x(q)``.

    Exact formula

    .. math::

       c_n(x)=\frac{(-1)^n}{2(2n)!}
       \sum_{k=0}^{2n}(-1)^k {2n\choose k}
       f^{(k)}(x)f^{(2n-k)}(x).

    Thus ``2*c_n = L_n[f](x)`` in the standard extended-Laguerre notation.
    """
    if not isinstance(n, int) or n < 0:
        raise ValueError("n must be a non-negative integer")
    x = mp.mpf(x)
    z = mp.mpc(x)
    derivatives = [f(z)] + [mp.diff(f, z, k) for k in range(1, 2 * n + 1)]
    total = mp.mpc(0)
    for k in range(2 * n + 1):
        total += (
            (-1) ** k
            * mp.binomial(2 * n, k)
            * derivatives[k]
            * derivatives[2 * n - k]
        )
    value = ((-1) ** n) * total / (2 * mp.factorial(2 * n))
    return mp.re(value)


def transverse_q_coefficients(
    f: ComplexFn, x: float | mp.mpf, through: int
) -> list[mp.mpf]:
    """Return ``[c_0(x),...,c_through(x)]`` using one derivative table."""
    if not isinstance(through, int) or through < 0:
        raise ValueError("through must be a non-negative integer")
    x = mp.mpf(x)
    z = mp.mpc(x)
    derivatives = [f(z)] + [mp.diff(f, z, k) for k in range(1, 2 * through + 1)]
    out: list[mp.mpf] = []
    for n in range(through + 1):
        total = mp.mpc(0)
        for k in range(2 * n + 1):
            total += (
                (-1) ** k
                * mp.binomial(2 * n, k)
                * derivatives[k]
                * derivatives[2 * n - k]
            )
        out.append(mp.re(((-1) ** n) * total / (2 * mp.factorial(2 * n))))
    return out


def extended_laguerre_value(
    f: ComplexFn, x: float | mp.mpf, n: int
) -> mp.mpf:
    r"""Return the classical extended Laguerre operator ``L_n[f](x)``."""
    return 2 * transverse_q_coefficient(f, x, n)


def transverse_partition_q(
    f: ComplexFn, x: float | mp.mpf, q: complex | mp.mpf | mp.mpc
) -> mp.mpc:
    r"""Evaluate ``Q_x(q)=1/2 f(x+i sqrt(q)) f(x-i sqrt(q))``.

    The displayed square root is only a numerical representative. Exact
    mathematics is branch-independent because the product is even in sqrt(q).
    """
    x = mp.mpf(x)
    q = mp.mpc(q)
    r = mp.sqrt(q)
    return mp.mpf("0.5") * f(mp.mpc(x) + 1j * r) * f(mp.mpc(x) - 1j * r)


def jensen_from_laguerre_coefficients(
    coefficients: Sequence[float | mp.mpf], y: float | mp.mpf
) -> mp.mpf:
    r"""Evaluate the finite weighted hierarchy producing ``d_y^2 Z``.

    If ``coefficients[n]=L_n[f](x)`` and the hierarchy terminates (e.g. for a
    polynomial f), the return value equals exactly

        H_f(x+i y) = sum_{n>=1} n(2n-1)L_n[f](x)y^(2n-2).

    For an infinite hierarchy this is a truncation and must be classified as
    numerical only.
    """
    y = mp.mpf(y)
    total = mp.mpf("0")
    for n in range(1, len(coefficients)):
        total += n * (2 * n - 1) * mp.mpf(coefficients[n]) * y ** (2 * n - 2)
    return total


def real_zero_pair_q_factor(
    gamma: float | mp.mpf, x: float | mp.mpf
) -> tuple[mp.mpf, mp.mpf, mp.mpf]:
    r"""q-coefficients contributed by one real zero pair ``+-gamma``.

    .. math::

       |1-(x+i\sqrt q)^2/\gamma^2|^2
       = a_0+a_1 q+a_2 q^2,

    with all three coefficients non-negative for real x and nonzero gamma.
    """
    gamma = mp.mpf(gamma)
    x = mp.mpf(x)
    if gamma == 0:
        raise ValueError("gamma must be nonzero")
    g2 = gamma * gamma
    g4 = g2 * g2
    return (
        (g2 - x * x) ** 2 / g4,
        2 * (g2 + x * x) / g4,
        1 / g4,
    )


def finite_real_zero_q_coefficients(
    gammas: Sequence[float | mp.mpf],
    x: float | mp.mpf,
    *,
    scale: float | mp.mpf = 1,
) -> list[mp.mpf]:
    r"""Exact coefficient convolution for ``f(z)=scale*prod(1-z^2/gamma^2)``."""
    x = mp.mpf(x)
    scale = mp.mpf(scale)
    coeffs = [mp.mpf("0.5") * scale * scale]
    for gamma in gammas:
        factor = real_zero_pair_q_factor(gamma, x)
        nxt = [mp.mpf("0")] * (len(coeffs) + 2)
        for i, a in enumerate(coeffs):
            for j, b in enumerate(factor):
                nxt[i + j] += a * b
        coeffs = nxt
    return coeffs


def xi_transverse_q_coefficients(
    x: float | mp.mpf, through: int
) -> list[mp.mpf]:
    """Finite high-precision diagnostic coefficients for Riemann Xi."""
    return transverse_q_coefficients(xi_fourier_entire, x, through)


def quartic_non_lp(z: complex | mp.mpf | mp.mpc) -> mp.mpc:
    """Adversarial real entire polynomial ``1+z^4`` with non-real zeros."""
    z = mp.mpc(z)
    return 1 + z**4


def quartic_first_gate_exact(x: float | mp.mpf) -> mp.mpf:
    r"""Exact q^1 coefficient for ``1+z^4``: ``2*x^2*(x^4-3)``."""
    x = mp.mpf(x)
    return 2 * x * x * (x**4 - 3)


def real_zero_product_function(
    gammas: Sequence[float | mp.mpf], *, scale: float | mp.mpf = 1
) -> ComplexFn:
    """Return a finite even real-rooted control polynomial."""
    gs = tuple(mp.mpf(g) for g in gammas)
    if any(g == 0 for g in gs):
        raise ValueError("all gammas must be nonzero")
    c = mp.mpf(scale)

    def f(z: mp.mpc) -> mp.mpc:
        z = mp.mpc(z)
        out = mp.mpc(c)
        for gamma in gs:
            out *= 1 - (z / gamma) ** 2
        return out

    return f


def real_axis_first_gate_matches_jensen(
    f: ComplexFn, x: float | mp.mpf
) -> mp.mpf:
    """Residual ``L_1[f](x)-H_f(x)`` on the real axis."""
    x = mp.mpf(x)
    return extended_laguerre_value(f, x, 1) - hermitian_jensen_value(f, mp.mpc(x))
